---
title: "Práctica final"
author: "Pilar Ruiz Navarro, Lucas Fehlau Arbulu"
date: "`r Sys.Date()`"
output:
  html_document: 
    toc: true
    toc_depth: 2
    number_sections: false
    toc_float: 
      collapsed: false
      smooth_scroll: false
  pdf_document:
    keep_tex: true
---


Esquema del trabajo de acuerdo al guión:
# Análisis exploratorio univariante
## a) Recodificaciones/agrupaciones de datos/variables (preprocesado)
## b) Valores perdidos
## c) Análisis descriptivo (summary, código de clase)
## d) Outliers (código de clase)
## e) Comprobar normalidad. qqplot
## f) Otros

# Análisis exploratorio multivariante
## a)Correlación (código de clase. test de Bartlett)
## b) Si se han tratado los outliers, ACP (código de clase)
## c) Si no se han tratado los NA, (código de clase)
## d) Estudio posibilidad de aplicar ACP y aplicarlo(código de clase)
## e) Elegir número de variables y aplicar AF(código de clase)
## f) Normalidad multivariante (código de clase, tema 5)
## g) Clasificador (código de clase)
### Lineal
### Cuadrático
## h) Validar modelos 
## i) Análisis cluster


<!-- 
Esquema del trabajo de ejemplo de Prado:
# Preprocesamiento de datos
## Descripción
## Carga de datos
## Valores perdidos
## Análisis exploratorio
## Outliers

# ACP
# AF

# AD
## Lineal
## Cuadrático
-->


# Abstract 
<!-- Opcional, supongo -->


# Introducción


# Read the data

```{r}
# data <- read.csv()

```


# Univariate exploratory analysis

## Valores faltantes

<!-- qqplots, etc -->

# Distribución multivariante

